from app.api.v1.legal.schemas import LegalDocumentResponse

LEGAL_CONTENT = {
    "terms": "Terms and Conditions\n\nIntroduction\nThynk provides AI-assisted prompt generation services. Eligibility\nYou must provide accurate account information and comply with applicable law. User accounts\nUsers are responsible for keeping credentials secure. Subscriptions and billing\nPaid features renew based on the selected plan unless cancelled. Acceptable use\nDo not use Thynk for harmful, fraudulent, or abusive activity. AI-generated outputs\nYou are responsible for reviewing generated content before use. Intellectual property\nThynk owns the service and software; users retain rights to lawful input they provide. Account termination\nThynk may suspend accounts that violate these terms. Limitation of liability\nThe service is provided on an as-available basis. Changes to terms\nWe may update these terms from time to time. Contact\nsupport@thynk.app",
    "privacy": "Privacy Policy\n\nIntroduction\nThynk collects account, usage, and support information required to operate the service. Information collected\nThis includes profile data, prompt requests, payment metadata, and support history. How data is used\nWe use data to provide the app, improve prompt quality, secure accounts, and support subscriptions. AI processing\nPrompt input may be processed by integrated AI providers. Payment processing\nPayments are handled by third-party providers such as Paystack and Stripe. Data storage\nData is stored securely using managed infrastructure and access controls. User rights\nUsers can request account deletion and profile updates. Security\nWe use hashing, JWT, access controls, and audit logging. Data deletion\nDeleted accounts are soft-deleted first for operational safety and compliance workflows. Changes to policy\nWe may update this policy. Contact\nsupport@thynk.app",
    "refund-policy": "Refund Policy\n\nSubscription payments\nSubscriptions are billed in advance based on the selected plan. Failed payments\nFailed payments may suspend or limit access until resolved. Refund eligibility\nRefunds may be considered when a duplicate charge, billing defect, or service issue is confirmed. Non-refundable situations\nUsed subscription periods, abuse, and policy violations are generally not refundable. How to contact support\nContact support@thynk.app with your payment reference and account email.",
}


def get_legal_document(slug: str) -> LegalDocumentResponse:
    return LegalDocumentResponse(slug=slug, title=slug.replace("-", " ").title(), content=LEGAL_CONTENT[slug])
